spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

app.security.jwt.secret=${APP_SECURITY_JWT_SECRET}
app.security.seed.admin.username=${APP_SECURITY_SEED_ADMIN_USERNAME}
app.security.seed.admin.password=${APP_SECURITY_SEED_ADMIN_PASSWORD}
app.security.seed.operador.username=${APP_SECURITY_SEED_OPERADOR_USERNAME}
app.security.seed.operador.password=${APP_SECURITY_SEED_OPERADOR_PASSWORD}
app.security.seed.analista.username=${APP_SECURITY_SEED_ANALISTA_USERNAME}
app.security.seed.analista.password=${APP_SECURITY_SEED_ANALISTA_PASSWORD}

simulator.api.enabled=${SIMULATOR_API_ENABLED:false}
simulator.api.url=${SIMULATOR_API_URL}
simulator.api.connect-timeout-ms=${SIMULATOR_API_CONNECT_TIMEOUT_MS:2000}
simulator.api.read-timeout-ms=${SIMULATOR_API_READ_TIMEOUT_MS:30000}
