spring.application.name=monitoramento-espacial-app
server.port=8080

# Le do compose (com fallback para desenvolvimento local)
spring.datasource.url=jdbc:postgresql://ep-tiny-dust-adys1axb-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WhI5DaSvtXo1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.security.jwt.secret=monitoramento-espacial-jwt-secret-com-32-caracteres-minimos
app.security.jwt.expiration-ms=28800000
app.security.seed.admin.username=admin
app.security.seed.admin.password=admin123
app.security.seed.operador.username=operador
app.security.seed.operador.password=operador123
app.security.seed.analista.username=analista
app.security.seed.analista.password=analista123
