spring.application.name=monitoramento-espacial-app
server.port=8080
spring.profiles.default=local

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

app.security.jwt.expiration-ms=${APP_SECURITY_JWT_EXPIRATION_MS:28800000}

simulator.api.enabled=${SIMULATOR_API_ENABLED:false}
simulator.api.url=${SIMULATOR_API_URL:http://localhost:8000}
simulator.api.connect-timeout-ms=${SIMULATOR_API_CONNECT_TIMEOUT_MS:2000}
simulator.api.read-timeout-ms=${SIMULATOR_API_READ_TIMEOUT_MS:30000}
